# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import swim_pb2 as swim__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in swim_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FailureDetectorStub(object):
    """gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/swim.FailureDetector/Ping',
                request_serializer=swim__pb2.PingRequest.SerializeToString,
                response_deserializer=swim__pb2.PingResponse.FromString,
                _registered_method=True)
        self.IndirectPing = channel.unary_unary(
                '/swim.FailureDetector/IndirectPing',
                request_serializer=swim__pb2.IndirectPingRequest.SerializeToString,
                response_deserializer=swim__pb2.IndirectPingResponse.FromString,
                _registered_method=True)


class FailureDetectorServicer(object):
    """gRPC service definition
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndirectPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FailureDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=swim__pb2.PingRequest.FromString,
                    response_serializer=swim__pb2.PingResponse.SerializeToString,
            ),
            'IndirectPing': grpc.unary_unary_rpc_method_handler(
                    servicer.IndirectPing,
                    request_deserializer=swim__pb2.IndirectPingRequest.FromString,
                    response_serializer=swim__pb2.IndirectPingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swim.FailureDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swim.FailureDetector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FailureDetector(object):
    """gRPC service definition
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swim.FailureDetector/Ping',
            swim__pb2.PingRequest.SerializeToString,
            swim__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndirectPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swim.FailureDetector/IndirectPing',
            swim__pb2.IndirectPingRequest.SerializeToString,
            swim__pb2.IndirectPingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DisseminationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Disseminate = channel.unary_unary(
                '/swim.Dissemination/Disseminate',
                request_serializer=swim__pb2.DisseminationRequest.SerializeToString,
                response_deserializer=swim__pb2.DisseminationResponse.FromString,
                _registered_method=True)
        self.Join = channel.unary_unary(
                '/swim.Dissemination/Join',
                request_serializer=swim__pb2.JoinRequest.SerializeToString,
                response_deserializer=swim__pb2.JoinResponse.FromString,
                _registered_method=True)


class DisseminationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Disseminate(self, request, context):
        """When a failure is detected, this RPC multicasts the info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Join(self, request, context):
        """New node join process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisseminationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Disseminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Disseminate,
                    request_deserializer=swim__pb2.DisseminationRequest.FromString,
                    response_serializer=swim__pb2.DisseminationResponse.SerializeToString,
            ),
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=swim__pb2.JoinRequest.FromString,
                    response_serializer=swim__pb2.JoinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swim.Dissemination', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swim.Dissemination', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Dissemination(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Disseminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swim.Dissemination/Disseminate',
            swim__pb2.DisseminationRequest.SerializeToString,
            swim__pb2.DisseminationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swim.Dissemination/Join',
            swim__pb2.JoinRequest.SerializeToString,
            swim__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
